# Uncomment this line to define a global platform for your project

use_frameworks!

platform :ios, '9.0'

target 'Qiu Suo' do

pod 'Kingfisher', '~> 1.6'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Alamofire', '~> 2.0'
pod 'MJRefresh'

end

target 'Qiu SuoTests' do

end

target 'Qiu SuoUITests' do

end

